name: port + recon for domain updated

on:
  workflow_dispatch:
    inputs:
      domain_name:
        required: true
        description: domain name

        
jobs:
  subdomain-wali:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout this repo
        run: sudo su
        uses: actions/checkout@v2






        
      - name: Fetch bbht repo & Setup runner
        run: |
          sudo su
          chmod +x scripts/*
          ./scripts/install-bash.sh
        
      - name: find ports for "${{ github.event.inputs.domain_name }}"
        run: |
          sudo su
          source ~/.bash_profile

          mkdir -p output/$domain
          cd output/$domain

          echo "${{ github.event.inputs.domain_name }}" > all.txt

          naabu -scan-type SYN -l all.txt -c 40 -p 70-500 -nmap-cli 'nmap --privileged -nv -sSV -A -oN --script nmap-vulners,vulscan nmap_scan.txt' -o naabu_portscan.txt
        

      - name: Checking for alive subdomains  
        run: |
          sudo su   
          source ~/.bash_profile   

          cat naabu_portscan.txt | httprobe -c 100 | tee -a alive2.txt
          cat alive2.txt | sort -u | tee -a alive.txt
          rm alive2.txt



      

      - name: Create local changes + Commit changes
        run: |
          git add .
          git config --local user.email "user@netanmangal.me"
          git config --global user.name "untucdX"
          git commit -m "report for ${{ github.event.inputs.domain_name }} added" -a --allow-empty
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
